### ISSUE TITLE
I've found a bug in your 8-lines sample code!

### ISSUE THREAD

**Issue by slowpeek** [xahlee/xah_emacs_init#4]
Good day Sir!

I'm learning elisp with your awesome tutorials. One of the code samples took me much time to understand why it didn't work. Here it is:

```lisp
(defun wrap-markup-region ()
  "Insert a markup <b></b> around a region."
  (interactive)
  (save-excursion
    (goto-char (region-end))
    (insert "</b>")
    (goto-char (region-beginning))
    (insert "<b>")))
```
It works as supposed if only you select text left-to-right. But if you try making a selection right-to-left (so that the point is the left edge of the region), it doesn't wrap the region with `<b></b>`.

In case the selection is made right-to-left the problem is the first `goto-char` does collapse the region. Hence `region-beginning` and `region-end` return the same value.

Here is the fixed code:

```lisp
(defun wrap-markup-region ()
  "Insert a markup <b></b> around a region."
  (interactive)
  (when (use-region-p)
    (save-excursion
      (let ((b (region-beginning))) ; <== save region beginning
        (goto-char (region-end))
        (insert "</b>")
        (goto-char b) ; <== use the saved position
        (insert "<b>")))))
```

This way it works as supposed it both cases.

Your sample code is located at http://ergoemacs.org/emacs/elisp_examples.html

**Comment by xahlee** [comment]
thanks. corrected.
